### ISSUE TITLE
Caching widgets

### ISSUE THREAD

**Issue by jonleverrier** [carlcs/craft-diywidget#11]
Amazing plugin! 

I've been using it to show some specific Commerce order data which I want to refresh every 24 hours. 

I've wrapped my widget twig output in `{% cache using key "some-key-value" for 24 hours %}`. For some reason, this is not being respected. The widget updates when ever the order data is changed.

Is there anything in the plugin that would stop the cache tag from working here?

Thanks again for an amazing plugin!

**Comment by carlcs** [comment]
Hi Jon, what you’re describing is actually expected behaviour of Craft’s template caching. Caches are invalidated when elements within the tags are updated (see https://craftcms.com/docs/4.x/dev/tags.html#cache-clearing).

I don‘t think there’s an option to opt-out of this feature. But what you could do is to run the expensive queries in a custom module and cache them using Yii Data Caches `Craft::$app->getCache()->getOrSet()`.

**Comment by jonleverrier** [comment]
Thanks for getting back to me @carlcs. I thought by setting a custom `key` with a `for` value changed the default behaviour.

I'm going to try your suggestion - sounds more promising!

Thanks once again.
